# This workflow builds and optionally runs a Go project (server and client)
# For more information: https://docs.github.com/en/actions

name: Go

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Download dependencies
      run: go mod tidy

    - name: Build server
      run: go run ./server.go

    - name: Build client
      run: go run ./client/client.go

    # Optional: Run the server and client (not typical in CI; better for test stage)
    # This may hang if server waits indefinitely — skip or use test framework
    # - name: Run server
    #   run: go run ./server.go &
    # - name: Run client
    #   run: go run ./client/client.go
